dependencies:
  #- <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default : development
  APIsepolia:
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify : False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify : False
  ganachelocal : 
    verify : False
  development:
    verify : False
